// Writes src/generated/forms.ts from the app's own configuration
// (consent-app/src/config/statements.ts, questions.ts and copy.ts), so the
// statement ids, versions, wording and answer options live in one place and
// the server, the validation and the export's data dictionaries follow.
// Runs as part of `npm run build`. Do not edit the generated file.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';

const here = path.dirname(new URL(import.meta.url).pathname);
const configDir = path.resolve(here, '../../../src/config');
const outFile = path.resolve(here, '../src/generated/forms.ts');

/** Loads one of the app's config modules (plain TypeScript with no imports) by transpiling it on the fly. */
async function load(name) {
  const source = fs.readFileSync(path.join(configDir, `${name}.ts`), 'utf8');
  const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } });
  const tmp = path.join(os.tmpdir(), `mpmb-config-${name}-${process.pid}.mjs`);
  fs.writeFileSync(tmp, outputText);
  try {
    return await import(pathToFileURL(tmp).href);
  } finally {
    fs.unlinkSync(tmp);
  }
}

const [statements, questions, copy] = await Promise.all([load('statements'), load('questions'), load('copy')]);

const form = (f) => ({
  id: f.id,
  version: f.version,
  statements: f.statements.map((s) => ({ id: s.id, version: s.version, kind: s.kind, label: s.label, text: s.text, coveredBySignature: Boolean(s.coveredBySignature) })),
});
const generated = {
  parentConsentForm: form(statements.parentConsentForm),
  childAssentForm: form(statements.childAssentForm),
  informationVersion: copy.parentInformationVersion.version,
  parentQuestionsForm: {
    id: questions.parentQuestionsForm.id,
    version: questions.parentQuestionsForm.version,
    questions: questions.parentQuestionsForm.questions.map((q) =>
      q.type === 'choice'
        ? { id: q.id, version: q.version, type: 'choice', label: q.label, text: q.text, options: q.options.map((o) => ({ value: o.value, label: o.label })) }
        : { id: q.id, version: q.version, type: 'text', label: q.label, text: q.text, maxLength: q.maxLength },
    ),
  },
};

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, `// Generated by scripts/generate-forms.mjs from consent-app/src/config. Do not edit; edit the app's config and rebuild.\nexport const generated = ${JSON.stringify(generated, null, 2)} as const;\n`);
console.log(`generated ${path.relative(process.cwd(), outFile)}: ${generated.parentConsentForm.id} ${generated.parentConsentForm.version}, ${generated.childAssentForm.id} ${generated.childAssentForm.version}, information ${generated.informationVersion}, ${generated.parentQuestionsForm.id} ${generated.parentQuestionsForm.version}`);
