// Writes src/generated/forms.ts from the app's own configuration
// (consent-app/src/config/statements.ts, questions.ts and copy.ts, and the
// social media break study's src/lab/config.ts and cleaner.ts), so the
// statement ids, versions, wording, answer options and file allow-lists live
// in one place and the server, the validation and the export's data
// dictionaries follow. Runs as part of `npm run build`. Do not edit the
// generated file.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';

const here = path.dirname(new URL(import.meta.url).pathname);
const appSrc = path.resolve(here, '../../../src');
const outFile = path.resolve(here, '../src/generated/forms.ts');

/** Loads one of the app's modules (plain TypeScript with no runtime imports) by transpiling it on the fly. */
async function load(name) {
  const source = fs.readFileSync(path.join(appSrc, `${name}.ts`), 'utf8');
  const { outputText } = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } });
  const tmp = path.join(os.tmpdir(), `mpmb-config-${name.replace(/[\\/]/g, '-')}-${process.pid}.mjs`);
  fs.writeFileSync(tmp, outputText);
  try {
    return await import(pathToFileURL(tmp).href);
  } finally {
    fs.unlinkSync(tmp);
  }
}

const [statements, questions, copy, lab, cleaner] = await Promise.all([load('config/statements'), load('config/questions'), load('config/copy'), load('lab/config'), load('lab/cleaner')]);

const form = (f) => ({
  id: f.id,
  version: f.version,
  statements: f.statements.map((s) => ({ id: s.id, version: s.version, kind: s.kind, label: s.label, text: s.text, coveredBySignature: Boolean(s.coveredBySignature) })),
});
const generated = {
  parentConsentForm: form(statements.parentConsentForm),
  childAssentForm: form(statements.childAssentForm),
  informationVersion: copy.parentInformationVersion.version,
  parentQuestionsForm: {
    id: questions.parentQuestionsForm.id,
    version: questions.parentQuestionsForm.version,
    questions: questions.parentQuestionsForm.questions.map((q) =>
      q.type === 'choice'
        ? { id: q.id, version: q.version, type: 'choice', label: q.label, text: q.text, options: q.options.map((o) => ({ value: o.value, label: o.label })) }
        : { id: q.id, version: q.version, type: 'text', label: q.label, text: q.text, maxLength: q.maxLength },
    ),
  },
  // The social media break study (adults): required statements plus an optional record-linkage choice.
  labConsentForm: {
    id: lab.labConsentForm.id,
    version: lab.labConsentForm.version,
    title: lab.labConsentForm.title,
    statements: lab.labConsentForm.statements.map((s) => ({ id: s.id, version: s.version, kind: s.kind, label: s.label, text: s.text })),
  },
  labInformationVersion: lab.labInformationVersion.version,
  labStudy: {
    studyId: lab.labStudy.studyId,
    minAge: lab.labStudy.minAge,
    maxAge: lab.labStudy.maxAge,
    maxArchiveBytes: lab.labStudy.maxArchiveBytes,
    maxScreenshots: lab.labStudy.maxScreenshots,
    participantCodePattern: lab.PARTICIPANT_CODE.source,
  },
  cleaner: {
    version: cleaner.CLEANER_VERSION,
    allowedFiles: cleaner.ALLOWED_CLEANED_FILES,
    categories: cleaner.categories.map((c) => ({ id: c.id, platform: c.platform, title: c.title })),
  },
};

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, `// Generated by scripts/generate-forms.mjs from consent-app/src. Do not edit; edit the app's config and rebuild.\nexport const generated = ${JSON.stringify(generated, null, 2)} as const;\n`);
console.log(
  `generated ${path.relative(process.cwd(), outFile)}: ${generated.parentConsentForm.id} ${generated.parentConsentForm.version}, ${generated.childAssentForm.id} ${generated.childAssentForm.version}, information ${generated.informationVersion}, ${generated.parentQuestionsForm.id} ${generated.parentQuestionsForm.version}, ${generated.labConsentForm.id} ${generated.labConsentForm.version}, lab information ${generated.labInformationVersion}, cleaner ${generated.cleaner.version}`,
);
